name: travel
description: travel app
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  dartz: ^0.8.9
  fluro: ^1.6.1
  badges: ^1.1.1
  get_it: ^4.0.0
  shimmer: ^1.1.0
  oktoast: ^2.3.1+1
  equatable: ^1.1.1
  expandable: ^4.1.2
  flutter_bloc: ^3.2.0
  extended_list: ^0.1.4
  waterfall_flow: ^0.1.3
  flutter_swiper: ^1.1.6
  extended_image: ^0.7.1
  cupertino_icons: ^0.1.2
  flutter_spinkit: ^4.1.2
  pull_to_refresh: ^1.5.8
  pin_code_text_field: ^1.5.1
  shared_preferences: ^0.5.6+2
  multi_image_picker: ^4.6.5+rc.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:
  uses-material-design: true
  fonts:
    - family: IconFont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: PingFangRegular
      fonts:
        - asset: assets/fonts/PingFangRegular.ttf
    - family: PingFangSCLight
      fonts:
        - asset: assets/fonts/PingFangSCLight.otf
    - family: PingFangSCThin
      fonts:
        - asset: assets/fonts/PingFangSCThin.otf
  assets:
    - assets/images/login_background.jpg
    - assets/images/suggest_food.png
    - assets/images/suggest_guide.png
    - assets/images/suggest_qa.png
    - assets/images/suggest_view.png
    - assets/images/number1.png
    - assets/images/number2.png
    - assets/images/number3.png
    - assets/images/number4.png
    - assets/images/number5.png
    - assets/images/number6.png
    - assets/images/number7.png
    - assets/images/number8.png
    - assets/images/number9.png
